In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/electricity_2024_2025.csv")
df.head()

                  Unnamed: 0     0
0  2024-01-01 00:00:00+01:00  0.10
1  2024-01-01 01:00:00+01:00  0.01
2  2024-01-01 02:00:00+01:00  0.02
3  2024-01-01 03:00:00+01:00  0.00
4  2024-01-01 04:00:00+01:00 -0.01

In [8]:
df.rename(columns={"Unnamed: 0": "date"}).set_index("date")

                               0
date
2024-01-01 00:00:00+01:00   0.10
2024-01-01 01:00:00+01:00   0.01
2024-01-01 02:00:00+01:00   0.02
2024-01-01 03:00:00+01:00   0.00
2024-01-01 04:00:00+01:00  -0.01
...                          ...
2025-12-31 23:00:00+01:00  97.52
2025-12-31 23:15:00+01:00  88.36
2025-12-31 23:30:00+01:00  83.98
2025-12-31 23:45:00+01:00  77.68
2026-01-01 00:00:00+01:00  95.95

[24170 rows x 1 columns]